<a href="https://colab.research.google.com/github/paulmunozpauta/Curso_Introduccion_Ciencia_Datos/blob/main/Notebooks/M01_Primeros%20pasos_Python_Google_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
  <img src="https://github.com/paulmunozpauta/Curso_Introduccion_Ciencia_Datos/raw/main/Static/Imgs/UdeC_color_horizontal.jpg" width="500">
</p>

<p align="center"><b style="font-size:28px;">Facultad de Ingeniería Agrícola</b></p>
<p align="center"><b style="font-size:28px;">Introducción a la Ciencia de Datos</b></p>
<hr>
<p align="center"><b style="font-size:28px;">Contacto</b></p>
<p align="center">
  paulmunoz@udec.cl<br>
  https://paulmunoz.com
</p>

# Introducción a la Ciencia de Datos
## Módulo 1: Introducción a la ciencia de datos

En este notebook conoceremos el entorno de trabajo que utilizaremos durante el curso y algunos conceptos básicos de Python necesarios para trabajar con datos.

No se requiere experiencia previa en programación.

In [76]:
print("Hola, Ciencia de Datos!")

Hola, Ciencia de Datos!

In [77]:
estacion = "Bernardo O'Higgins, Chillán"
anio = 2025
precipitacion = 12.5
lluvia = True

In [78]:
print(type(estacion))
print(type(anio))
print(type(precipitacion))
print(type(lluvia))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

In [79]:
precipitacion_dia1 = 12.5
precipitacion_dia2 = 7.8

precipitacion_total = precipitacion_dia1 + precipitacion_dia2

print(precipitacion_total)

20.3

In [80]:
precipitaciones = [0.0, 5.2, 12.4, 0.0, 3.7]

print(precipitaciones)

[0.0, 5.2, 12.4, 0.0, 3.7]

In [81]:
precipitaciones[0]

0.0

In [82]:
precipitaciones[1:4]

[5.2, 12.4, 0.0]

In [83]:
estacion = {
    "nombre": "Bernardo O'Higgins",
    "ciudad": "Chillán",
    "region": "Ñuble",
    "variable": "Precipitación"
}

estacion

{'nombre': "Bernardo O'Higgins",
 'ciudad': 'Chillán',
 'region': 'Ñuble',
 'variable': 'Precipitación'}

In [84]:
estacion["ciudad"]

'Chillán'

## Librerías

Python puede ampliar sus funcionalidades mediante librerías.

Durante el curso utilizaremos principalmente:

- **Pandas:** organización y análisis de datos.
- **NumPy:** operaciones numéricas.
- **Matplotlib:** visualización.
- **Scikit-learn:** aprendizaje automático.

In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [86]:
datos = pd.DataFrame({
    "fecha": ["2025-06-01", "2025-06-02", "2025-06-03", "2025-06-04"],
    "precipitacion_mm": [0.0, 12.5, 4.2, 0.0]
})

datos

        fecha  precipitacion_mm
0  2025-06-01               0.0
1  2025-06-02              12.5
2  2025-06-03               4.2
3  2025-06-04               0.0

In [88]:
datos["precipitacion_mm"]

0     0.0
1    12.5
2     4.2
3     0.0
Name: precipitacion_mm, dtype: float64

In [89]:
datos["precipitacion_mm"].max()

12.5

In [90]:
datos["precipitacion_mm"].mean()

np.float64(4.175)