<a href="https://colab.research.google.com/github/paulmunozpauta/Curso_Introduccion_Ciencia_Datos/blob/main/Notebooks/M01_Primeros%20pasos_Python_Google_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
  <img src="https://github.com/paulmunozpauta/Curso_Introduccion_Ciencia_Datos/raw/main/Static/Imgs/UdeC_color_horizontal.jpg" width="500">
</p>

<p align="center"><b style="font-size:28px;">Facultad de Ingeniería Agrícola</b></p>
<p align="center"><b style="font-size:28px;">Introducción a la Ciencia de Datos</b></p>
<hr>
<p align="center"><b style="font-size:28px;">Contacto</b></p>
<p align="center">
  paulmunoz@udec.cl<br>
  https://paulmunoz.com
</p>

## Módulo 1: Primeros pasos con Python y Colab

En este notebook conoceremos el entorno de trabajo que utilizaremos durante el curso y algunos conceptos básicos de Python necesarios para trabajar con datos.

No se requiere experiencia previa en programación.

## 1. Nuestro primer código en Python

Python es un lenguaje de programación ampliamente utilizado en ciencia de datos debido a su facilidad de uso y a la gran cantidad de herramientas disponibles para trabajar con datos.

En Google Colab, el código se escribe y ejecuta en **celdas de código**. Para ejecutar una celda puedes hacer clic en el botón ▶ ubicado a la izquierda o utilizar `Shift + Enter`.

Comenzaremos utilizando la función `print()`, que permite mostrar información en pantalla.

In [2]:
print("Hola, Ciencia de Datos!")

Hola, Ciencia de Datos!

La instrucción anterior utiliza la función `print()` para mostrar un texto. El texto se encuentra entre comillas porque Python lo interpreta como una cadena de caracteres (*string*).

A lo largo del curso no será necesario memorizar todos los comandos. Lo importante será comprender qué queremos hacer con los datos y aprender a utilizar las herramientas apropiadas para hacerlo.

## 2. Variables y tipos de datos

Una **variable** permite almacenar información para utilizarla posteriormente. Podemos pensar en una variable como un nombre que asignamos a un determinado valor.

Por ejemplo, en un análisis climático podemos almacenar el nombre de una estación, un año, una cantidad de precipitación o indicar si ocurrió o no precipitación durante un día.

Python determina automáticamente el tipo de información almacenada en cada variable.

In [3]:
estacion = "Bernardo O'Higgins, Chillán"
anio = 2025
precipitacion = 12.5
lluvia = True

En el ejemplo anterior hemos creado cuatro variables con distintos tipos de información:

- `estacion` contiene texto.
- `anio` contiene un número entero.
- `precipitacion` contiene un número decimal.
- `lluvia` contiene un valor lógico que puede ser verdadero (`True`) o falso (`False`).

Podemos utilizar la función `type()` para conocer el tipo de dato almacenado en una variable.

In [4]:
print(type(estacion))
print(type(anio))
print(type(precipitacion))
print(type(lluvia))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

Los principales tipos que observamos son:

- `str`: texto o cadena de caracteres.
- `int`: números enteros.
- `float`: números con decimales.
- `bool`: valores lógicos (`True` o `False`).

Reconocer los tipos de datos será importante más adelante, ya que las operaciones que podemos realizar dependen del tipo de información almacenada.

## 3. Operaciones básicas

Las variables numéricas pueden utilizarse para realizar operaciones matemáticas.

Supongamos que conocemos la precipitación registrada durante dos días consecutivos y queremos calcular la precipitación acumulada.

In [5]:
precipitacion_dia1 = 12.5
precipitacion_dia2 = 7.8

precipitacion_total = precipitacion_dia1 + precipitacion_dia2

print(precipitacion_total)

20.3

Python suma los valores almacenados en `precipitacion_dia1` y `precipitacion_dia2` y guarda el resultado en una nueva variable llamada `precipitacion_total`.

Este ejemplo es sencillo, pero la misma lógica permite automatizar operaciones sobre miles o millones de observaciones.

## 4. Listas

Hasta ahora cada variable almacenaba un único valor. Sin embargo, normalmente trabajaremos con muchas observaciones.

Una **lista** permite almacenar varios elementos dentro de una misma variable. Los elementos se escriben entre corchetes `[]` y se separan mediante comas.

Por ejemplo, podemos almacenar la precipitación observada durante cinco días:

In [6]:
precipitaciones = [0.0, 5.2, 12.4, 0.0, 3.7]

print(precipitaciones)

[0.0, 5.2, 12.4, 0.0, 3.7]

Cada elemento de una lista ocupa una posición denominada **índice**.

Una característica importante de Python es que la numeración comienza en **0**. Por lo tanto:

- `precipitaciones[0]` corresponde al primer elemento.
- `precipitaciones[1]` corresponde al segundo.
- `precipitaciones[2]` corresponde al tercero.

In [7]:
precipitaciones[0]

0.0

También podemos seleccionar varios elementos. La siguiente instrucción selecciona los elementos desde la posición 1 hasta antes de la posición 4:

In [8]:
precipitaciones

[0.0, 5.2, 12.4, 0.0, 3.7]

In [9]:
precipitaciones[1:4]

[5.2, 12.4, 0.0]

## 5. Diccionarios

Una lista es útil cuando almacenamos una secuencia de valores. Sin embargo, en algunas situaciones necesitamos asociar cada valor con una característica determinada.

Un **diccionario** almacena información mediante pares `clave: valor`.

Por ejemplo, podemos representar algunas características de una estación meteorológica:

In [10]:
estacion = {
    "nombre": "Bernardo O'Higgins",
    "ciudad": "Chillán",
    "region": "Ñuble",
    "variable": "Precipitación"
}

estacion

{'nombre': "Bernardo O'Higgins",
 'ciudad': 'Chillán',
 'region': 'Ñuble',
 'variable': 'Precipitación'}

En este caso, `nombre`, `ciudad`, `region` y `variable` son las **claves** del diccionario.

Podemos consultar un valor indicando su clave:

In [11]:
estacion["ciudad"]

'Chillán'

## 6. Librerías de Python

Python incluye muchas herramientas básicas, pero una de sus principales ventajas es que puede ampliar sus capacidades mediante **librerías**.

Una librería es un conjunto de funciones desarrolladas para realizar determinadas tareas. En ciencia de datos existen librerías especializadas para manipular datos, realizar cálculos, construir gráficos o desarrollar modelos de aprendizaje automático.

Durante el curso utilizaremos principalmente:

- **Pandas:** organización, manipulación y análisis de datos tabulares.
- **NumPy:** operaciones y cálculos numéricos.
- **Matplotlib:** creación de gráficos y visualizaciones.
- **Scikit-learn:** herramientas de aprendizaje automático.

Antes de utilizar una librería debemos importarla.

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Las expresiones `pd`, `np` y `plt` son abreviaciones utilizadas convencionalmente para referirnos a estas librerías.

Por ejemplo, en lugar de escribir `pandas` cada vez que necesitamos utilizar una función de esta librería, utilizaremos `pd`.

Google Colab ya incluye estas librerías, por lo que no es necesario instalarlas.

## 7. Introducción a los DataFrames

Los datos utilizados en ingeniería suelen estar organizados en forma tabular: cada **fila** representa una observación y cada **columna** representa una variable.

Pandas utiliza una estructura denominada **DataFrame** para trabajar con este tipo de información.

Un DataFrame puede entenderse inicialmente como una tabla similar a una hoja de cálculo, pero que podemos manipular y analizar mediante instrucciones de Python.

Crearemos un pequeño DataFrame con datos diarios de precipitación:

In [13]:
datos = pd.DataFrame({
    "fecha": ["2025-06-01", "2025-06-02", "2025-06-03", "2025-06-04"],
    "precipitacion_mm": [0.0, 12.5, 4.2, 0.0]
})

datos

        fecha  precipitacion_mm
0  2025-06-01               0.0
1  2025-06-02              12.5
2  2025-06-03               4.2
3  2025-06-04               0.0

Nuestro DataFrame contiene:

- **4 filas:** cuatro observaciones diarias.
- **2 columnas:** `fecha` y `precipitacion_mm`.

La columna `fecha` identifica cuándo ocurrió cada observación, mientras que `precipitacion_mm` contiene la cantidad de precipitación registrada.

Podemos comprobar qué tipo de objeto hemos creado:

In [17]:
type(datos)

pandas.core.frame.DataFrame

El resultado `pandas.core.frame.DataFrame` indica que la variable `datos` contiene un DataFrame de Pandas.

Podemos seleccionar una columna indicando su nombre entre corchetes:

In [14]:
datos["precipitacion_mm"]

0     0.0
1    12.5
2     4.2
3     0.0
Name: precipitacion_mm, dtype: float64

Al seleccionar una sola columna de un DataFrame, Pandas devuelve una estructura denominada **Series**.

Por ahora basta con entender que una Series representa una columna de datos. En los próximos notebooks aprenderemos a trabajar con DataFrames y Series con mayor profundidad.

In [15]:
datos["precipitacion_mm"].max()

12.5

In [16]:
datos["precipitacion_mm"].mean()

np.float64(4.175)

## 8. Hacer preguntas a nuestros datos

El objetivo de utilizar Python no es solamente escribir código. Queremos utilizar el código para **responder preguntas a partir de los datos**.

Por ejemplo:

**¿Cuál fue la precipitación diaria máxima registrada en nuestro pequeño conjunto de datos?**