<a href="https://colab.research.google.com/github/paulmunozpauta/Curso_Introduccion_Ciencia_Datos/blob/main/Static/M02_02_Organizaci%C3%B3n_preparaci%C3%B3n_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
  <img src="https://github.com/paulmunozpauta/Curso_Introduccion_Ciencia_Datos/raw/main/Static/Imgs/UdeC_color_horizontal.jpg" width="500">
</p>

<p align="center"><b style="font-size:28px;">Facultad de Ingeniería Agrícola</b></p>
<p align="center"><b style="font-size:28px;">Introducción a la Ciencia de Datos</b></p>
<hr>
<p align="center"><b style="font-size:28px;">Contacto</b></p>
<p align="center">
  paulmunoz@udec.cl<br>
  https://paulmunoz.com
</p>

# Introducción a la Ciencia de Datos
## Módulo 2: Organización y preparación de datos

### Notebook 2: Selección y manipulación de datos


En el notebook anterior aprendimos a importar una serie climática, explorar la estructura de un `DataFrame`, trabajar con fechas e identificar datos faltantes.

En este notebook aprenderemos a **seleccionar, filtrar, ordenar y modificar datos** utilizando Pandas.

Trabajaremos nuevamente con la serie diaria de precipitación de la estación **Bernardo O'Higgins, Chillán**, obtenida desde el Explorador Climático CR2.

Al finalizar este notebook podrás:

- seleccionar columnas de un DataFrame;

- seleccionar filas utilizando posiciones o etiquetas;

- utilizar `.loc[]` e `.iloc[]`;

- filtrar observaciones mediante condiciones;

- combinar varias condiciones;

- seleccionar periodos específicos;

- ordenar datos;

- crear nuevas variables;

- modificar y eliminar columnas.

## 1. Importar las librerías

Utilizaremos nuevamente la librería `pandas`, que contiene las principales herramientas para manipular datos tabulares.

También utilizaremos `matplotlib` para realizar algunas visualizaciones simples que nos ayuden a comprobar los resultados de nuestros filtros.

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

## 2. Cargar los datos

Comenzaremos cargando nuevamente el archivo utilizado en el notebook anterior.

Recuerda que Google Colab funciona en un entorno temporal. Por esta razón, cuando iniciamos una nueva sesión debemos volver a cargar los archivos que utilizaremos.

Ejecuta la siguiente celda y selecciona el archivo:

`BernardoOHigginsChillan.xlsx`

In [2]:
from google.colab import files

uploaded = files.upload()

Saving BernardoOHigginsChillan.xlsx to BernardoOHigginsChillan.xlsx

## 3. Leer el archivo con Pandas

El archivo contiene una hoja llamada `Serie`.

Utilizaremos la función `read_excel()` de Pandas para importar los datos.

In [5]:
datos = pd.read_excel("BernardoOHigginsChillan.xlsx", sheet_name="Serie")
datos.head()

   agno  mes  dia  valor
0  1950    1    1    0.0
1  1950    1    2    0.0
2  1950    1    3    0.0
3  1950    1    4    0.0
4  1950    1    5    0.0

Antes de continuar, realizaremos nuevamente algunas operaciones de preparación utilizadas en el notebook anterior.

Crearemos una columna de fecha y cambiaremos los nombres `agno` y `valor` por nombres más fáciles de interpretar.

In [6]:
datos["fecha"] = pd.to_datetime(
    dict(
        year=datos["agno"],
        month=datos["mes"],
        day=datos["dia"]
    )
)

datos = datos.rename(columns={
    "agno": "anio",
    "valor": "precipitacion_mm"
})

datos = datos[
    ["fecha", "anio", "mes", "dia", "precipitacion_mm"]
]

datos.head()

       fecha  anio  mes  dia  precipitacion_mm
0 1950-01-01  1950    1    1               0.0
1 1950-01-02  1950    1    2               0.0
2 1950-01-03  1950    1    3               0.0
3 1950-01-04  1950    1    4               0.0
4 1950-01-05  1950    1    5               0.0

## 3. Seleccionar columnas

Un DataFrame puede contener muchas variables. En determinadas etapas del análisis solamente necesitaremos trabajar con algunas de ellas.

Podemos seleccionar una columna utilizando su nombre entre corchetes.

In [7]:
datos["precipitacion_mm"]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
25532    4.2
25533    0.0
25534    0.0
25535    0.0
25536    0.0
Name: precipitacion_mm, Length: 25537, dtype: float64

Al seleccionar una sola columna, Pandas devuelve una estructura denominada `Series`.

Podemos comprobarlo utilizando `type()`.

In [8]:
type(datos["precipitacion_mm"])

pandas.core.series.Series

También podemos seleccionar varias columnas.

En ese caso debemos proporcionar una lista con los nombres de las columnas que queremos conservar.

In [9]:
datos[["fecha", "precipitacion_mm"]].head()

       fecha  precipitacion_mm
0 1950-01-01               0.0
1 1950-01-02               0.0
2 1950-01-03               0.0
3 1950-01-04               0.0
4 1950-01-05               0.0

## 4. Seleccionar filas mediante `iloc`

Pandas permite seleccionar registros según su **posición** dentro del DataFrame utilizando `.iloc[]`.

Al igual que las listas de Python, las posiciones comienzan en `0`.

Por lo tanto:

- posición `0` → primera fila;
- posición `1` → segunda fila;
- posición `2` → tercera fila.

In [10]:
datos.iloc[0]

fecha               1950-01-01 00:00:00
anio                               1950
mes                                   1
dia                                   1
precipitacion_mm                    0.0
Name: 0, dtype: object

In [11]:
datos.iloc[0:5]

       fecha  anio  mes  dia  precipitacion_mm
0 1950-01-01  1950    1    1               0.0
1 1950-01-02  1950    1    2               0.0
2 1950-01-03  1950    1    3               0.0
3 1950-01-04  1950    1    4               0.0
4 1950-01-05  1950    1    5               0.0

La expresión `0:5` selecciona desde la posición `0` hasta antes de la posición `5`.

Por lo tanto, obtenemos las primeras cinco observaciones.

In [12]:
datos.iloc[0:5, [0, 4]]

       fecha  precipitacion_mm
0 1950-01-01               0.0
1 1950-01-02               0.0
2 1950-01-03               0.0
3 1950-01-04               0.0
4 1950-01-05               0.0

En este ejemplo:

- `0:5` selecciona las primeras cinco filas.
- `[0, 4]` selecciona la primera y quinta columna.

`iloc` trabaja siempre utilizando **posiciones numéricas**.

## 5. Seleccionar datos mediante `.loc`

Mientras `.iloc[]` utiliza posiciones, `.loc[]` permite seleccionar información utilizando **etiquetas o nombres de columnas**.

Esto suele hacer que el código sea más fácil de leer.